package com.max.booking_flights_data.repositories

import com.max.booking_flights_domain.repositories.FlightToConcertsOffersRepository

internal class FlightToConcertsOffersRepositoryImpl:FlightToConcertsOffersRepository {
}