package com.max.booking_flights_data.repositories

import com.max.booking_flights_domain.repositories.SaveDeparturesTownRepository

internal class SaveDeparturesTownRepositoryImpl: SaveDeparturesTownRepository {
}