package com.max.booking_flights_data.usecases

import com.max.booking_flights_domain.repositories.FlightToConcertsOffersRepository

internal class FlightToConcertsOffersUseCaseImpl:FlightToConcertsOffersRepository {
}